### PR TITLE
Changed URL to request UUID.

### PR DESCRIPTION
**Pull request by Keksnet**
The uuid is now requested from the MojangAPI.
Please do not use an external side.

### CODE REVIEW

**Comment by KennyTV** [comment]
This will block your entire server from accessing the Mojang API for 20-30 minutes if you do a request for a player twice.

**Comment by Keksnet** [comment]
The MojangAPI does not block my requests if I send the same request three times so I do not know what you mean.

**Comment by KennyTV** [comment]
Oh right sorry, that was for another end point. Nethertheless, I don't want people to possibly scream about the limits that *are* in place, + the mojang api is going to be deprecated soon and replaced with minecraftservices - using Electroid's api spares me from having to update it later

**Comment by Keksnet** [comment]
Where do you get this information, that the MojangAPI is going to be deprecated? And the limits are in place but 600 requests per 10 minutes are enough. I don't think that a server adds more than 600 people in 10 minutes to the whitelist.

**Comment by Keksnet** [comment]
And - please correct me if I am wrong - but the ashcon api ist limited also to 1 million requests per day and that results to 6944 requests per 10 minutes.

**Comment by KennyTV** [comment]
Not limited to, but that's the amount it usually gets (but doesn't all forward to Mojang by caching data). The info for the new Minecraft services site is related the soonish MS account migration; can't remember where that was exactly, but Mojang employees announced it a while back

**Comment by Keksnet** [comment]
Are you sure that it is not only the new authentication sheme? I can't find something on the internet about it and also wiki.vg don't says anythink about that.

**Pull request closed without merging**
