### PR TITLE
Maven cleanup

### PR DESCRIPTION
**Pull request by PSandro**
Did some cleanup on the maven module names and added a script to download the jar file of ServerListPlus and install it in local maven repository, since there is no official maven repository for that.

My maven setup couldn't load the child modules (that easy) because of the differences between directory names and artifactIds, thats the main reason for the name change beside clean look :grinning:

### CODE REVIEW

**Comment by KennyTV** [comment]
Thanks, looks good! Sadly I did some module and directory changes in the dev branch, could you pull that branch and adapt your changes to that?

**Comment by PSandro** [comment]
This should work. Hopefully i didn't miss anything... there were some merge conflicts :thinking:

**Comment by KennyTV** [comment]
I think it would be best to create a clean, new branch off the dev one and quickly adapt the changes, shouldn't take too long for you :p

**Comment by PSandro** [comment]
yep, you're right. That is probably better... :smile:

**Pull request closed without merging**
